"""create donation model

Revision ID: 310e9cf2f5df
Revises: 3904b8bf124a
Create Date: 2022-12-25 05:00:26.923911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310e9cf2f5df'
down_revision = '3904b8bf124a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
