"""f

Revision ID: 4556134fcc5a
Revises: 21d797511824
Create Date: 2022-12-29 13:54:58.011472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4556134fcc5a'
down_revision = '21d797511824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
