"""upgrade

Revision ID: 3904b8bf124a
Revises: ffeaf978e815
Create Date: 2022-12-25 04:53:37.176385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3904b8bf124a'
down_revision = 'ffeaf978e815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charityproject', sa.Column('full_amount', sa.Integer(), nullable=False))
    op.add_column('charityproject', sa.Column('invested_amount', sa.Integer(), nullable=True))
    op.add_column('charityproject', sa.Column('fully_invested', sa.Boolean(), nullable=True))
    op.add_column('charityproject', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('charityproject', sa.Column('close_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charityproject', 'close_date')
    op.drop_column('charityproject', 'create_date')
    op.drop_column('charityproject', 'fully_invested')
    op.drop_column('charityproject', 'invested_amount')
    op.drop_column('charityproject', 'full_amount')
    # ### end Alembic commands ###
