"""upgrade donations

Revision ID: 21d797511824
Revises: 02ea56db8c16
Create Date: 2022-12-25 06:41:38.999604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d797511824'
down_revision = '02ea56db8c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
